-- FlashPortal V31 Cloud Saves foundation

create table if not exists public.game_saves (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  save_key text not null default 'default',
  save_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now(),
  unique (user_id, game_id, save_key)
);

alter table public.game_saves enable row level security;

create policy "Users can read their own saves"
on public.game_saves
for select
using (auth.uid() = user_id);

create policy "Users can insert their own saves"
on public.game_saves
for insert
with check (auth.uid() = user_id);

create policy "Users can update their own saves"
on public.game_saves
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own saves"
on public.game_saves
for delete
using (auth.uid() = user_id);
