create table if not exists public.creator_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  bio text,
  avatar_url text,
  creator_level text default 'New Creator',
  verified_creator boolean default false,
  is_fdc_publisher boolean default false,
  follower_count int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.game_reviews (
  id bigint generated by default as identity primary key,
  game_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  review text not null check (char_length(review) <= 800),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (game_id, user_id)
);

create table if not exists public.creator_payouts (
  id bigint generated by default as identity primary key,
  creator_id uuid references auth.users(id) on delete set null,
  game_id text,
  gross_amount_cents int not null default 0,
  creator_amount_cents int not null default 0,
  platform_amount_cents int not null default 0,
  split_creator_percent int not null default 85,
  split_platform_percent int not null default 15,
  stripe_session_id text,
  status text default 'pending',
  created_at timestamptz default now()
);

alter table public.creator_profiles enable row level security;
alter table public.game_reviews enable row level security;
alter table public.creator_payouts enable row level security;

create policy "Creator profiles are public"
on public.creator_profiles for select using (true);

create policy "Users can insert their own creator profile"
on public.creator_profiles for insert with check (auth.uid() = user_id);

create policy "Users can update their own creator profile"
on public.creator_profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Reviews are public"
on public.game_reviews for select using (true);

create policy "Users can insert their own reviews"
on public.game_reviews for insert with check (auth.uid() = user_id);

create policy "Users can update their own reviews"
on public.game_reviews for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Creators can read their own payouts"
on public.creator_payouts for select using (auth.uid() = creator_id);
