create table if not exists public.game_submissions (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  category text,
  website_url text,
  thumbnail_url text,
  zip_url text,
  status text not null default 'pending',
  is_fdc_original boolean default false,
  is_featured boolean default false,
  price_cents int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.game_submissions enable row level security;

create policy if not exists "Anyone can read approved games"
on public.game_submissions
for select
using (status = 'approved');

create policy if not exists "Creators can read their own submissions"
on public.game_submissions
for select
using (auth.uid() = creator_id);

create policy if not exists "Creators can insert their own submissions"
on public.game_submissions
for insert
with check (auth.uid() = creator_id);

create policy if not exists "Creators can update their own pending submissions"
on public.game_submissions
for update
using (auth.uid() = creator_id and status = 'pending')
with check (auth.uid() = creator_id and status = 'pending');

create policy if not exists "Public can read game files"
on storage.objects
for select
using (bucket_id in ('game-files', 'game-thumbnails'));

create policy if not exists "Users can upload game files"
on storage.objects
for insert
with check (
  auth.uid() is not null
  and bucket_id in ('game-files', 'game-thumbnails')
);

create policy if not exists "Users can update own game files"
on storage.objects
for update
using (
  auth.uid() is not null
  and bucket_id in ('game-files', 'game-thumbnails')
);
