create table if not exists public.game_ratings (
  id bigint generated by default as identity primary key,
  game_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating int not null check (rating between 1 and 5),
  updated_at timestamptz default now(),
  unique (game_id, user_id)
);

alter table public.game_ratings enable row level security;

create policy "Anyone can read game ratings"
on public.game_ratings
for select
using (true);

create policy "Users can insert their own ratings"
on public.game_ratings
for insert
with check (auth.uid() = user_id);

create policy "Users can update their own ratings"
on public.game_ratings
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
