-- FlashPortal V40 backend policies and persistent counters
-- Run this in Supabase SQL Editor.

create table if not exists public.game_play_counts (
  game_id text primary key,
  plays bigint not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.game_play_counts (game_id, plays)
values
  ('how-many-rings', 0),
  ('legacy-league', 0)
on conflict (game_id) do nothing;

alter table public.game_play_counts enable row level security;

drop policy if exists "Public can read game play counts" on public.game_play_counts;
create policy "Public can read game play counts"
on public.game_play_counts
for select
using (true);

create or replace function public.increment_game_play(target_game_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_count bigint;
begin
  insert into public.game_play_counts (game_id, plays, updated_at)
  values (target_game_id, 1, now())
  on conflict (game_id)
  do update set plays = public.game_play_counts.plays + 1, updated_at = now()
  returning plays into new_count;

  return new_count;
end;
$$;

grant execute on function public.increment_game_play(text) to anon, authenticated;

create table if not exists public.admin_roles (
  id bigint generated by default as identity primary key,
  email text not null unique,
  role text not null default 'admin',
  permissions jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  added_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.admin_roles enable row level security;

drop policy if exists "Owner can manage admin roles" on public.admin_roles;
create policy "Owner can manage admin roles"
on public.admin_roles
for all
using ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com')
with check ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

drop policy if exists "Admins can read their own role" on public.admin_roles;
create policy "Admins can read their own role"
on public.admin_roles
for select
using (lower(email) = lower(auth.jwt() ->> 'email'));

-- Ensure game_submissions has expected columns.
create table if not exists public.game_submissions (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references auth.users(id) on delete cascade,
  title text,
  game_title text,
  category text,
  description text,
  website_url text,
  zip_path text,
  thumbnail_path text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.game_submissions enable row level security;

drop policy if exists "Approved submissions are public" on public.game_submissions;
create policy "Approved submissions are public"
on public.game_submissions
for select
using (status = 'approved');

drop policy if exists "Creators can read their own submissions" on public.game_submissions;
create policy "Creators can read their own submissions"
on public.game_submissions
for select
using (auth.uid() = creator_id);

drop policy if exists "Creators can insert their own submissions" on public.game_submissions;
create policy "Creators can insert their own submissions"
on public.game_submissions
for insert
with check (auth.uid() = creator_id);

drop policy if exists "Creators can update their own pending submissions" on public.game_submissions;
create policy "Creators can update their own pending submissions"
on public.game_submissions
for update
using (auth.uid() = creator_id and status = 'pending')
with check (auth.uid() = creator_id and status = 'pending');

drop policy if exists "Owner and admins can read submissions" on public.game_submissions;
create policy "Owner and admins can read submissions"
on public.game_submissions
for select
using (
  (auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com'
  or exists (
    select 1 from public.admin_roles ar
    where lower(ar.email) = lower(auth.jwt() ->> 'email')
      and ar.active = true
      and coalesce((ar.permissions ->> 'submissions')::boolean, false) = true
  )
);

drop policy if exists "Owner and admins can update submissions" on public.game_submissions;
create policy "Owner and admins can update submissions"
on public.game_submissions
for update
using (
  (auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com'
  or exists (
    select 1 from public.admin_roles ar
    where lower(ar.email) = lower(auth.jwt() ->> 'email')
      and ar.active = true
      and coalesce((ar.permissions ->> 'submissions')::boolean, false) = true
  )
)
with check (
  (auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com'
  or exists (
    select 1 from public.admin_roles ar
    where lower(ar.email) = lower(auth.jwt() ->> 'email')
      and ar.active = true
      and coalesce((ar.permissions ->> 'submissions')::boolean, false) = true
  )
);
