-- FlashPortal V41 backend fixes
-- Run this in Supabase SQL Editor.

create table if not exists public.game_submissions (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references auth.users(id) on delete cascade,
  title text,
  category text,
  description text,
  website_url text,
  zip_path text,
  thumbnail_path text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.game_submissions add column if not exists title text;
alter table public.game_submissions add column if not exists category text;
alter table public.game_submissions add column if not exists description text;
alter table public.game_submissions add column if not exists website_url text;
alter table public.game_submissions add column if not exists zip_path text;
alter table public.game_submissions add column if not exists thumbnail_path text;
alter table public.game_submissions add column if not exists status text not null default 'pending';
alter table public.game_submissions add column if not exists created_at timestamptz not null default now();
alter table public.game_submissions add column if not exists updated_at timestamptz not null default now();

alter table public.game_submissions enable row level security;

drop policy if exists "Creators can insert their own submissions" on public.game_submissions;
create policy "Creators can insert their own submissions"
on public.game_submissions for insert
with check (auth.uid() = creator_id);

drop policy if exists "Creators can read their own submissions" on public.game_submissions;
create policy "Creators can read their own submissions"
on public.game_submissions for select
using (auth.uid() = creator_id);

drop policy if exists "Owner can read all submissions" on public.game_submissions;
create policy "Owner can read all submissions"
on public.game_submissions for select
using ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

drop policy if exists "Owner can update submissions" on public.game_submissions;
create policy "Owner can update submissions"
on public.game_submissions for update
using ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com')
with check ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

create table if not exists public.game_play_counts (
  game_id text primary key,
  plays bigint not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.game_play_counts (game_id, plays)
values
  ('how-many-rings', 0),
  ('legacy-league', 0),
  ('guess-the-celeb', 0),
  ('guess-the-word', 0)
on conflict (game_id) do nothing;

alter table public.game_play_counts enable row level security;

drop policy if exists "Public can read game play counts" on public.game_play_counts;
create policy "Public can read game play counts"
on public.game_play_counts for select
using (true);

create or replace function public.increment_game_play(target_game_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_count bigint;
begin
  insert into public.game_play_counts (game_id, plays, updated_at)
  values (target_game_id, 1, now())
  on conflict (game_id)
  do update set plays = public.game_play_counts.plays + 1, updated_at = now()
  returning plays into new_count;

  return new_count;
end;
$$;

grant execute on function public.increment_game_play(text) to anon, authenticated;

notify pgrst, 'reload schema';
