-- FlashPortal V43 social/upload backend
-- Run this after V41/V42 SQL if you want database-backed playlists/reviews later.
-- Current V43 UI stores playlists/reviews locally first, so it works immediately.

create table if not exists public.game_reviews (
  id bigint generated by default as identity primary key,
  game_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  rating int check (rating between 1 and 5),
  review text,
  created_at timestamptz not null default now()
);

alter table public.game_reviews enable row level security;

drop policy if exists "Public can read reviews" on public.game_reviews;
create policy "Public can read reviews"
on public.game_reviews for select
using (true);

drop policy if exists "Users can insert reviews" on public.game_reviews;
create policy "Users can insert reviews"
on public.game_reviews for insert
with check (auth.uid() = user_id or user_id is null);

create table if not exists public.user_playlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  created_at timestamptz not null default now(),
  unique(user_id, game_id)
);

alter table public.user_playlists enable row level security;

drop policy if exists "Users can manage own playlist" on public.user_playlists;
create policy "Users can manage own playlist"
on public.user_playlists for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Upload sanity: make sure columns exist.
alter table public.game_submissions add column if not exists title text;
alter table public.game_submissions add column if not exists category text;
alter table public.game_submissions add column if not exists description text;
alter table public.game_submissions add column if not exists website_url text;
alter table public.game_submissions add column if not exists zip_path text;
alter table public.game_submissions add column if not exists thumbnail_path text;
alter table public.game_submissions add column if not exists status text not null default 'pending';

notify pgrst, 'reload schema';
