-- FlashPortal V44 upload permission fix
-- Run this in Supabase SQL Editor.
-- This fixes: "permission denied for table game_submissions"

-- 1) Make sure the table exists and has every column the upload page uses.
create table if not exists public.game_submissions (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references auth.users(id) on delete cascade,
  title text,
  category text,
  description text,
  website_url text,
  zip_path text,
  thumbnail_path text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.game_submissions add column if not exists creator_id uuid references auth.users(id) on delete cascade;
alter table public.game_submissions add column if not exists title text;
alter table public.game_submissions add column if not exists category text;
alter table public.game_submissions add column if not exists description text;
alter table public.game_submissions add column if not exists website_url text;
alter table public.game_submissions add column if not exists zip_path text;
alter table public.game_submissions add column if not exists thumbnail_path text;
alter table public.game_submissions add column if not exists status text not null default 'pending';
alter table public.game_submissions add column if not exists created_at timestamptz not null default now();
alter table public.game_submissions add column if not exists updated_at timestamptz not null default now();

alter table public.game_submissions enable row level security;

-- 2) Remove older/conflicting policies and rebuild clean policies.
drop policy if exists "Approved submissions are public" on public.game_submissions;
drop policy if exists "Creators can read their own submissions" on public.game_submissions;
drop policy if exists "Creators can insert their own submissions" on public.game_submissions;
drop policy if exists "Creators can update their own pending submissions" on public.game_submissions;
drop policy if exists "Owner and admins can read submissions" on public.game_submissions;
drop policy if exists "Owner and admins can update submissions" on public.game_submissions;
drop policy if exists "Owner can read all submissions" on public.game_submissions;
drop policy if exists "Owner can update submissions" on public.game_submissions;

create policy "Approved submissions are public"
on public.game_submissions
for select
using (status = 'approved');

create policy "Creators can read their own submissions"
on public.game_submissions
for select
using (auth.uid() = creator_id);

create policy "Creators can insert own pending submissions"
on public.game_submissions
for insert
to authenticated
with check (
  auth.uid() = creator_id
  and coalesce(status, 'pending') = 'pending'
);

create policy "Creators can update own pending submissions"
on public.game_submissions
for update
to authenticated
using (auth.uid() = creator_id and status = 'pending')
with check (auth.uid() = creator_id and status = 'pending');

create policy "Owner can read all submissions"
on public.game_submissions
for select
to authenticated
using ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

create policy "Owner can update all submissions"
on public.game_submissions
for update
to authenticated
using ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com')
with check ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

-- 3) Make sure storage buckets exist.
insert into storage.buckets (id, name, public)
values
  ('game-files', 'game-files', false),
  ('game-thumbnails', 'game-thumbnails', true)
on conflict (id) do nothing;

-- 4) Storage policies for uploaded game ZIPs and thumbnails.
drop policy if exists "Creators can upload game files" on storage.objects;
drop policy if exists "Creators can read own game files" on storage.objects;
drop policy if exists "Creators can upload game thumbnails" on storage.objects;
drop policy if exists "Public can read game thumbnails" on storage.objects;

create policy "Creators can upload game files"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'game-files'
  and auth.uid()::text = split_part(name, '/', 1)
);

create policy "Creators can read own game files"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'game-files'
  and auth.uid()::text = split_part(name, '/', 1)
);

create policy "Creators can upload game thumbnails"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'game-thumbnails'
  and auth.uid()::text = split_part(name, '/', 1)
);

create policy "Public can read game thumbnails"
on storage.objects
for select
using (bucket_id = 'game-thumbnails');

-- 5) Force Supabase API schema refresh.
notify pgrst, 'reload schema';
