-- FlashPortal V45 backend fix
-- Run this in Supabase SQL Editor.
-- This is stronger than V44 and fixes permission denied errors for uploads.

create table if not exists public.game_submissions (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references auth.users(id) on delete cascade,
  title text,
  category text,
  description text,
  website_url text,
  zip_path text,
  thumbnail_path text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.game_submissions add column if not exists creator_id uuid references auth.users(id) on delete cascade;
alter table public.game_submissions add column if not exists title text;
alter table public.game_submissions add column if not exists category text;
alter table public.game_submissions add column if not exists description text;
alter table public.game_submissions add column if not exists website_url text;
alter table public.game_submissions add column if not exists zip_path text;
alter table public.game_submissions add column if not exists thumbnail_path text;
alter table public.game_submissions add column if not exists status text not null default 'pending';
alter table public.game_submissions add column if not exists created_at timestamptz not null default now();
alter table public.game_submissions add column if not exists updated_at timestamptz not null default now();

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.game_submissions to authenticated;
grant select on public.game_submissions to anon;
grant usage, select on all sequences in schema public to authenticated;

alter table public.game_submissions enable row level security;

drop policy if exists "Approved submissions are public" on public.game_submissions;
drop policy if exists "Creators can read their own submissions" on public.game_submissions;
drop policy if exists "Creators can insert own pending submissions" on public.game_submissions;
drop policy if exists "Creators can insert their own submissions" on public.game_submissions;
drop policy if exists "Creators can update own pending submissions" on public.game_submissions;
drop policy if exists "Owner can read all submissions" on public.game_submissions;
drop policy if exists "Owner can update all submissions" on public.game_submissions;

create policy "Approved submissions are public"
on public.game_submissions for select
using (status = 'approved');

create policy "Creators can read own submissions"
on public.game_submissions for select
to authenticated
using (auth.uid() = creator_id);

create policy "Creators can insert own submissions"
on public.game_submissions for insert
to authenticated
with check (auth.uid() = creator_id);

create policy "Creators can update own pending submissions"
on public.game_submissions for update
to authenticated
using (auth.uid() = creator_id and status = 'pending')
with check (auth.uid() = creator_id and status = 'pending');

create policy "Owner can read all submissions"
on public.game_submissions for select
to authenticated
using ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

create policy "Owner can update all submissions"
on public.game_submissions for update
to authenticated
using ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com')
with check ((auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

-- Storage
insert into storage.buckets (id, name, public)
values
  ('game-files', 'game-files', false),
  ('game-thumbnails', 'game-thumbnails', true)
on conflict (id) do nothing;

drop policy if exists "Creators can upload game files" on storage.objects;
drop policy if exists "Creators can read own game files" on storage.objects;
drop policy if exists "Creators can upload game thumbnails" on storage.objects;
drop policy if exists "Public can read game thumbnails" on storage.objects;

create policy "Creators can upload game files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'game-files');

create policy "Creators can read own game files"
on storage.objects for select
to authenticated
using (bucket_id = 'game-files');

create policy "Creators can upload game thumbnails"
on storage.objects for insert
to authenticated
with check (bucket_id = 'game-thumbnails');

create policy "Public can read game thumbnails"
on storage.objects for select
using (bucket_id = 'game-thumbnails');

-- Reviews table for future DB-backed reviews.
create table if not exists public.game_reviews (
  id bigint generated by default as identity primary key,
  game_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  rating int check (rating between 1 and 5),
  review text,
  created_at timestamptz not null default now()
);

grant select, insert on public.game_reviews to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
alter table public.game_reviews enable row level security;

drop policy if exists "Public can read reviews" on public.game_reviews;
drop policy if exists "Anyone can create reviews" on public.game_reviews;
create policy "Public can read reviews"
on public.game_reviews for select using (true);
create policy "Anyone can create reviews"
on public.game_reviews for insert with check (true);

-- Friends foundation.
create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users(id) on delete cascade,
  sender_email text,
  target text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

grant select, insert, update on public.friend_requests to authenticated;
alter table public.friend_requests enable row level security;

drop policy if exists "Users can create friend requests" on public.friend_requests;
drop policy if exists "Users can see related friend requests" on public.friend_requests;
create policy "Users can create friend requests"
on public.friend_requests for insert
to authenticated
with check (auth.uid() = sender_id);

create policy "Users can see related friend requests"
on public.friend_requests for select
to authenticated
using (auth.uid() = sender_id or lower(target) = lower(auth.jwt() ->> 'email'));

notify pgrst, 'reload schema';
