-- FlashPortal V46 backend fix
-- Run this in Supabase SQL Editor.
-- Fixes: Owner queue not seeing uploads, announcements, notifications, reviews, and proper friend requests.

grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- GAME SUBMISSIONS
create table if not exists public.game_submissions (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references auth.users(id) on delete cascade,
  creator_email text,
  title text,
  category text,
  description text,
  website_url text,
  zip_path text,
  thumbnail_path text,
  status text not null default 'pending',
  owner_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.game_submissions add column if not exists creator_email text;
alter table public.game_submissions add column if not exists title text;
alter table public.game_submissions add column if not exists category text;
alter table public.game_submissions add column if not exists description text;
alter table public.game_submissions add column if not exists website_url text;
alter table public.game_submissions add column if not exists zip_path text;
alter table public.game_submissions add column if not exists thumbnail_path text;
alter table public.game_submissions add column if not exists status text not null default 'pending';
alter table public.game_submissions add column if not exists owner_notes text;
alter table public.game_submissions add column if not exists updated_at timestamptz not null default now();

grant select, insert, update, delete on public.game_submissions to authenticated;
grant select on public.game_submissions to anon;

alter table public.game_submissions enable row level security;

drop policy if exists "Approved submissions are public" on public.game_submissions;
drop policy if exists "Creators can read own submissions" on public.game_submissions;
drop policy if exists "Creators can insert own submissions" on public.game_submissions;
drop policy if exists "Creators can update own pending submissions" on public.game_submissions;
drop policy if exists "Owner can read all submissions" on public.game_submissions;
drop policy if exists "Owner can update all submissions" on public.game_submissions;
drop policy if exists "Owner can delete submissions" on public.game_submissions;

create policy "Approved submissions are public"
on public.game_submissions for select
using (status = 'approved');

create policy "Creators can read own submissions"
on public.game_submissions for select
to authenticated
using (auth.uid() = creator_id);

create policy "Creators can insert own submissions"
on public.game_submissions for insert
to authenticated
with check (auth.uid() = creator_id);

create policy "Creators can update own pending submissions"
on public.game_submissions for update
to authenticated
using (auth.uid() = creator_id and status = 'pending')
with check (auth.uid() = creator_id and status = 'pending');

create policy "Owner can read all submissions"
on public.game_submissions for select
to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com', 'flashdustcorp@gmail.com'));

create policy "Owner can update all submissions"
on public.game_submissions for update
to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com', 'flashdustcorp@gmail.com'))
with check ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com', 'flashdustcorp@gmail.com'));

create policy "Owner can delete submissions"
on public.game_submissions for delete
to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com', 'flashdustcorp@gmail.com'));

-- STORAGE
insert into storage.buckets (id, name, public)
values
  ('game-files', 'game-files', false),
  ('game-thumbnails', 'game-thumbnails', true)
on conflict (id) do nothing;

drop policy if exists "Creators can upload game files" on storage.objects;
drop policy if exists "Creators can read own game files" on storage.objects;
drop policy if exists "Creators can upload game thumbnails" on storage.objects;
drop policy if exists "Public can read game thumbnails" on storage.objects;

create policy "Creators can upload game files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'game-files');

create policy "Creators can read own game files"
on storage.objects for select
to authenticated
using (bucket_id = 'game-files');

create policy "Creators can upload game thumbnails"
on storage.objects for insert
to authenticated
with check (bucket_id = 'game-thumbnails');

create policy "Public can read game thumbnails"
on storage.objects for select
using (bucket_id = 'game-thumbnails');

-- ANNOUNCEMENTS / NOTIFICATIONS
create table if not exists public.platform_announcements (
  id bigint generated by default as identity primary key,
  title text not null default 'FlashPortal Announcement',
  body text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_by_email text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

grant select on public.platform_announcements to anon, authenticated;
grant insert, update, delete on public.platform_announcements to authenticated;
alter table public.platform_announcements enable row level security;

drop policy if exists "Public can read active announcements" on public.platform_announcements;
drop policy if exists "Owner can manage announcements" on public.platform_announcements;

create policy "Public can read active announcements"
on public.platform_announcements for select
using (active = true);

create policy "Owner can manage announcements"
on public.platform_announcements for all
to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com', 'flashdustcorp@gmail.com'))
with check ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com', 'flashdustcorp@gmail.com'));

-- REVIEWS
create table if not exists public.game_reviews (
  id bigint generated by default as identity primary key,
  game_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  display_name text,
  rating int not null check (rating between 1 and 5),
  review text not null,
  created_at timestamptz not null default now()
);

grant select, insert on public.game_reviews to anon, authenticated;
alter table public.game_reviews enable row level security;

drop policy if exists "Public can read reviews" on public.game_reviews;
drop policy if exists "Anyone can create reviews" on public.game_reviews;

create policy "Public can read reviews"
on public.game_reviews for select
using (true);

create policy "Anyone can create reviews"
on public.game_reviews for insert
with check (rating between 1 and 5 and length(trim(review)) > 0);

-- FRIEND REQUESTS
create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users(id) on delete cascade,
  sender_email text not null,
  target text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

grant select, insert, update, delete on public.friend_requests to authenticated;
alter table public.friend_requests enable row level security;

drop policy if exists "Users can create friend requests" on public.friend_requests;
drop policy if exists "Users can see related friend requests" on public.friend_requests;
drop policy if exists "Users can update received friend requests" on public.friend_requests;

create policy "Users can create friend requests"
on public.friend_requests for insert
to authenticated
with check (
  auth.uid() = sender_id
  and lower(target) <> lower(auth.jwt() ->> 'email')
);

create policy "Users can see related friend requests"
on public.friend_requests for select
to authenticated
using (
  auth.uid() = sender_id
  or lower(target) = lower(auth.jwt() ->> 'email')
);

create policy "Users can update received friend requests"
on public.friend_requests for update
to authenticated
using (lower(target) = lower(auth.jwt() ->> 'email'))
with check (lower(target) = lower(auth.jwt() ->> 'email'));

notify pgrst, 'reload schema';
