-- FlashPortal V47 SQL hotfix
-- Run this in Supabase SQL Editor.
-- Fixes missing columns, duplicate policy errors, upload queue visibility, and review/rating tables.

grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- 1) Submissions table + missing creator_email column.
create table if not exists public.game_submissions (
  id bigint generated by default as identity primary key,
  creator_id uuid references auth.users(id) on delete cascade,
  creator_email text,
  title text,
  category text,
  description text,
  website_url text,
  zip_path text,
  thumbnail_path text,
  status text not null default 'pending',
  owner_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.game_submissions add column if not exists creator_id uuid references auth.users(id) on delete cascade;
alter table public.game_submissions add column if not exists creator_email text;
alter table public.game_submissions add column if not exists title text;
alter table public.game_submissions add column if not exists category text;
alter table public.game_submissions add column if not exists description text;
alter table public.game_submissions add column if not exists website_url text;
alter table public.game_submissions add column if not exists zip_path text;
alter table public.game_submissions add column if not exists thumbnail_path text;
alter table public.game_submissions add column if not exists status text not null default 'pending';
alter table public.game_submissions add column if not exists owner_notes text;
alter table public.game_submissions add column if not exists created_at timestamptz not null default now();
alter table public.game_submissions add column if not exists updated_at timestamptz not null default now();

grant select, insert, update, delete on public.game_submissions to authenticated;
grant select on public.game_submissions to anon;

alter table public.game_submissions enable row level security;

drop policy if exists "Approved submissions are public" on public.game_submissions;
drop policy if exists "Creators can read own submissions" on public.game_submissions;
drop policy if exists "Creators can insert own submissions" on public.game_submissions;
drop policy if exists "Creators can update own pending submissions" on public.game_submissions;
drop policy if exists "Creators can update own pending submissions" on public.game_submissions;
drop policy if exists "Owner can read all submissions" on public.game_submissions;
drop policy if exists "Owner can update all submissions" on public.game_submissions;
drop policy if exists "Owner can delete submissions" on public.game_submissions;

create policy "Approved submissions are public"
on public.game_submissions for select
using (status = 'approved');

create policy "Creators can read own submissions"
on public.game_submissions for select
to authenticated
using (auth.uid() = creator_id);

create policy "Creators can insert own submissions"
on public.game_submissions for insert
to authenticated
with check (auth.uid() = creator_id);

create policy "Creators can update own pending submissions"
on public.game_submissions for update
to authenticated
using (auth.uid() = creator_id and status = 'pending')
with check (auth.uid() = creator_id and status = 'pending');

create policy "Owner can read all submissions"
on public.game_submissions for select
to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com', 'flashdustcorp@gmail.com'));

create policy "Owner can update all submissions"
on public.game_submissions for update
to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com', 'flashdustcorp@gmail.com'))
with check ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com', 'flashdustcorp@gmail.com'));

create policy "Owner can delete submissions"
on public.game_submissions for delete
to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com', 'flashdustcorp@gmail.com'));

-- 2) Reviews/ratings table.
create table if not exists public.game_reviews (
  id bigint generated by default as identity primary key,
  game_id text,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  display_name text,
  rating int,
  review text,
  created_at timestamptz not null default now()
);

alter table public.game_reviews add column if not exists game_id text;
alter table public.game_reviews add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.game_reviews add column if not exists user_email text;
alter table public.game_reviews add column if not exists display_name text;
alter table public.game_reviews add column if not exists rating int;
alter table public.game_reviews add column if not exists review text;
alter table public.game_reviews add column if not exists created_at timestamptz not null default now();

update public.game_reviews set rating = 5 where rating is null;
update public.game_reviews set review = '' where review is null;
update public.game_reviews set game_id = 'unknown-game' where game_id is null;

alter table public.game_reviews alter column rating set not null;
alter table public.game_reviews alter column review set not null;
alter table public.game_reviews alter column game_id set not null;

alter table public.game_reviews drop constraint if exists game_reviews_rating_check;
alter table public.game_reviews add constraint game_reviews_rating_check check (rating between 1 and 5);

grant select, insert, update, delete on public.game_reviews to anon, authenticated;
alter table public.game_reviews enable row level security;

drop policy if exists "Public can read reviews" on public.game_reviews;
drop policy if exists "Anyone can create reviews" on public.game_reviews;
drop policy if exists "Users can edit their own reviews" on public.game_reviews;

create policy "Public can read reviews"
on public.game_reviews for select
using (true);

create policy "Anyone can create reviews"
on public.game_reviews for insert
with check (rating between 1 and 5 and length(trim(review)) > 0);

create policy "Users can edit their own reviews"
on public.game_reviews for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 3) Storage buckets for uploads.
insert into storage.buckets (id, name, public)
values
  ('game-files', 'game-files', false),
  ('game-thumbnails', 'game-thumbnails', true)
on conflict (id) do nothing;

drop policy if exists "Creators can upload game files" on storage.objects;
drop policy if exists "Creators can read own game files" on storage.objects;
drop policy if exists "Creators can upload game thumbnails" on storage.objects;
drop policy if exists "Public can read game thumbnails" on storage.objects;

create policy "Creators can upload game files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'game-files');

create policy "Creators can read own game files"
on storage.objects for select
to authenticated
using (bucket_id = 'game-files');

create policy "Creators can upload game thumbnails"
on storage.objects for insert
to authenticated
with check (bucket_id = 'game-thumbnails');

create policy "Public can read game thumbnails"
on storage.objects for select
using (bucket_id = 'game-thumbnails');

notify pgrst, 'reload schema';
