-- FlashPortal V49 ONE SQL FILE
-- Run this ONCE in Supabase SQL Editor.
-- This replaces the older V40/V44/V45/V46/V47 SQL attempts.

grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ---------- PLAY COUNTS ----------
create table if not exists public.game_play_counts (
  game_id text primary key,
  plays bigint not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.game_play_counts (game_id, plays)
values
  ('how-many-rings', 0),
  ('legacy-league', 0),
  ('guess-the-word', 0),
  ('guess-the-celeb', 0)
on conflict (game_id) do nothing;

alter table public.game_play_counts enable row level security;
grant select, insert, update on public.game_play_counts to anon, authenticated;

drop policy if exists "Public can read game play counts" on public.game_play_counts;
drop policy if exists "Anyone can upsert game play counts" on public.game_play_counts;

create policy "Public can read game play counts"
on public.game_play_counts for select using (true);

create policy "Anyone can upsert game play counts"
on public.game_play_counts for insert with check (true);

create or replace function public.increment_game_play(target_game_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_count bigint;
begin
  insert into public.game_play_counts (game_id, plays, updated_at)
  values (target_game_id, 1, now())
  on conflict (game_id)
  do update set plays = public.game_play_counts.plays + 1, updated_at = now()
  returning plays into new_count;
  return new_count;
end;
$$;

grant execute on function public.increment_game_play(text) to anon, authenticated;

-- ---------- SUBMISSIONS ----------
create table if not exists public.game_submissions (
  id bigint generated by default as identity primary key,
  creator_id uuid references auth.users(id) on delete set null,
  creator_email text,
  title text,
  category text,
  description text,
  website_url text,
  zip_path text,
  thumbnail_path text,
  status text not null default 'pending',
  owner_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.game_submissions add column if not exists creator_id uuid references auth.users(id) on delete set null;
alter table public.game_submissions add column if not exists creator_email text;
alter table public.game_submissions add column if not exists title text;
alter table public.game_submissions add column if not exists game_title text;
update public.game_submissions set title = coalesce(title, game_title) where title is null;
alter table public.game_submissions add column if not exists category text;
alter table public.game_submissions add column if not exists description text;
alter table public.game_submissions add column if not exists website_url text;
alter table public.game_submissions add column if not exists zip_path text;
alter table public.game_submissions add column if not exists thumbnail_path text;
alter table public.game_submissions add column if not exists status text not null default 'pending';
alter table public.game_submissions add column if not exists owner_notes text;
alter table public.game_submissions add column if not exists created_at timestamptz not null default now();
alter table public.game_submissions add column if not exists updated_at timestamptz not null default now();

alter table public.game_submissions enable row level security;
grant select, insert, update, delete on public.game_submissions to authenticated;
grant select on public.game_submissions to anon;

drop policy if exists "Approved submissions are public" on public.game_submissions;
drop policy if exists "Creators can read own submissions" on public.game_submissions;
drop policy if exists "Creators can read their own submissions" on public.game_submissions;
drop policy if exists "Creators can insert own submissions" on public.game_submissions;
drop policy if exists "Creators can insert their own submissions" on public.game_submissions;
drop policy if exists "Creators can update own pending submissions" on public.game_submissions;
drop policy if exists "Creators can update their own pending submissions" on public.game_submissions;
drop policy if exists "Owner can read all submissions" on public.game_submissions;
drop policy if exists "Owner can update all submissions" on public.game_submissions;
drop policy if exists "Owner can delete submissions" on public.game_submissions;
drop policy if exists "Owner and admins can read submissions" on public.game_submissions;
drop policy if exists "Owner and admins can update submissions" on public.game_submissions;

create policy "Approved submissions are public"
on public.game_submissions for select using (status = 'approved');

create policy "Creators can read own submissions"
on public.game_submissions for select to authenticated
using (auth.uid() = creator_id);

create policy "Creators can insert own submissions"
on public.game_submissions for insert to authenticated
with check (auth.uid() = creator_id);

create policy "Creators can update own pending submissions"
on public.game_submissions for update to authenticated
using (auth.uid() = creator_id and status = 'pending')
with check (auth.uid() = creator_id and status = 'pending');

create policy "Owner can read all submissions"
on public.game_submissions for select to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com','flashdustcorp@gmail.com'));

create policy "Owner can update all submissions"
on public.game_submissions for update to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com','flashdustcorp@gmail.com'))
with check ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com','flashdustcorp@gmail.com'));

create policy "Owner can delete submissions"
on public.game_submissions for delete to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com','flashdustcorp@gmail.com'));

-- ---------- REVIEWS ----------
create table if not exists public.game_reviews (
  id bigint generated by default as identity primary key,
  game_id text,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  display_name text,
  rating int,
  review text,
  created_at timestamptz not null default now()
);

alter table public.game_reviews add column if not exists game_id text;
alter table public.game_reviews add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.game_reviews add column if not exists user_email text;
alter table public.game_reviews add column if not exists display_name text;
alter table public.game_reviews add column if not exists rating int;
alter table public.game_reviews add column if not exists review text;
alter table public.game_reviews add column if not exists created_at timestamptz not null default now();

update public.game_reviews set game_id = 'unknown-game' where game_id is null;
update public.game_reviews set rating = 5 where rating is null;
update public.game_reviews set review = '' where review is null;

alter table public.game_reviews alter column game_id set not null;
alter table public.game_reviews alter column rating set not null;
alter table public.game_reviews alter column review set not null;

alter table public.game_reviews drop constraint if exists game_reviews_rating_check;
alter table public.game_reviews add constraint game_reviews_rating_check check (rating between 1 and 5);

alter table public.game_reviews enable row level security;
grant select, insert, update, delete on public.game_reviews to anon, authenticated;

drop policy if exists "Public can read reviews" on public.game_reviews;
drop policy if exists "Anyone can create reviews" on public.game_reviews;
drop policy if exists "Users can edit their own reviews" on public.game_reviews;
drop policy if exists "Users can insert reviews" on public.game_reviews;

create policy "Public can read reviews"
on public.game_reviews for select using (true);

create policy "Users can insert reviews"
on public.game_reviews for insert
with check (rating between 1 and 5 and length(trim(review)) > 0);

create policy "Users can edit their own reviews"
on public.game_reviews for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- ---------- ANNOUNCEMENTS / NOTIFICATIONS ----------
create table if not exists public.platform_announcements (
  id bigint generated by default as identity primary key,
  title text not null default 'FlashPortal Update',
  body text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_by_email text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.platform_announcements add column if not exists title text not null default 'FlashPortal Update';
alter table public.platform_announcements add column if not exists body text not null default '';
alter table public.platform_announcements add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.platform_announcements add column if not exists created_by_email text;
alter table public.platform_announcements add column if not exists active boolean not null default true;
alter table public.platform_announcements add column if not exists created_at timestamptz not null default now();

alter table public.platform_announcements enable row level security;
grant select on public.platform_announcements to anon, authenticated;
grant insert, update, delete on public.platform_announcements to authenticated;

drop policy if exists "Public can read active announcements" on public.platform_announcements;
drop policy if exists "Owner can create announcements" on public.platform_announcements;
drop policy if exists "Owner can update announcements" on public.platform_announcements;
drop policy if exists "Owner can delete announcements" on public.platform_announcements;

create policy "Public can read active announcements"
on public.platform_announcements for select using (active = true);

create policy "Owner can create announcements"
on public.platform_announcements for insert to authenticated
with check ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com','flashdustcorp@gmail.com'));

create policy "Owner can update announcements"
on public.platform_announcements for update to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com','flashdustcorp@gmail.com'))
with check ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com','flashdustcorp@gmail.com'));

create policy "Owner can delete announcements"
on public.platform_announcements for delete to authenticated
using ((auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com','flashdustcorp@gmail.com'));

-- ---------- FRIENDS ----------
create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users(id) on delete cascade,
  sender_email text,
  target text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.friend_requests add column if not exists sender_id uuid references auth.users(id) on delete cascade;
alter table public.friend_requests add column if not exists sender_email text;
alter table public.friend_requests add column if not exists target text;
alter table public.friend_requests add column if not exists status text not null default 'pending';
alter table public.friend_requests add column if not exists created_at timestamptz not null default now();
alter table public.friend_requests add column if not exists updated_at timestamptz not null default now();

alter table public.friend_requests enable row level security;
grant select, insert, update, delete on public.friend_requests to authenticated;

drop policy if exists "Users can insert friend requests" on public.friend_requests;
drop policy if exists "Users can see related friend requests" on public.friend_requests;
drop policy if exists "Users can update received friend requests" on public.friend_requests;

create policy "Users can insert friend requests"
on public.friend_requests for insert to authenticated
with check (auth.uid() = sender_id);

create policy "Users can see related friend requests"
on public.friend_requests for select to authenticated
using (
  auth.uid() = sender_id
  or lower(target) = lower(auth.jwt() ->> 'email')
);

create policy "Users can update received friend requests"
on public.friend_requests for update to authenticated
using (lower(target) = lower(auth.jwt() ->> 'email'))
with check (lower(target) = lower(auth.jwt() ->> 'email'));

-- ---------- STORAGE ----------
insert into storage.buckets (id, name, public)
values
  ('game-files', 'game-files', false),
  ('game-thumbnails', 'game-thumbnails', true)
on conflict (id) do nothing;

drop policy if exists "Creators can upload game files" on storage.objects;
drop policy if exists "Creators can read own game files" on storage.objects;
drop policy if exists "Owners can read all game files" on storage.objects;
drop policy if exists "Creators can upload game thumbnails" on storage.objects;
drop policy if exists "Public can read game thumbnails" on storage.objects;

create policy "Creators can upload game files"
on storage.objects for insert to authenticated
with check (bucket_id = 'game-files');

create policy "Creators can read own game files"
on storage.objects for select to authenticated
using (bucket_id = 'game-files');

create policy "Owners can read all game files"
on storage.objects for select to authenticated
using (bucket_id = 'game-files' and (auth.jwt() ->> 'email') in ('isaac.akinola122@gmail.com','flashdustcorp@gmail.com'));

create policy "Creators can upload game thumbnails"
on storage.objects for insert to authenticated
with check (bucket_id = 'game-thumbnails');

create policy "Public can read game thumbnails"
on storage.objects for select
using (bucket_id = 'game-thumbnails');

notify pgrst, 'reload schema';
