-- FlashPortal V50 Reviews/Ratings SQL
-- Run this in Supabase SQL Editor if reviews do not save publicly.

grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create table if not exists public.game_reviews (
  id bigint generated by default as identity primary key,
  game_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  display_name text,
  rating int not null check (rating between 1 and 5),
  review text not null,
  created_at timestamptz not null default now()
);

alter table public.game_reviews add column if not exists game_id text;
alter table public.game_reviews add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.game_reviews add column if not exists user_email text;
alter table public.game_reviews add column if not exists display_name text;
alter table public.game_reviews add column if not exists rating int;
alter table public.game_reviews add column if not exists review text;
alter table public.game_reviews add column if not exists created_at timestamptz not null default now();

update public.game_reviews set game_id = 'unknown-game' where game_id is null;
update public.game_reviews set rating = 5 where rating is null;
update public.game_reviews set review = '' where review is null;

alter table public.game_reviews alter column game_id set not null;
alter table public.game_reviews alter column rating set not null;
alter table public.game_reviews alter column review set not null;

alter table public.game_reviews drop constraint if exists game_reviews_rating_check;
alter table public.game_reviews add constraint game_reviews_rating_check check (rating between 1 and 5);

grant select, insert, update, delete on public.game_reviews to anon, authenticated;

alter table public.game_reviews enable row level security;

drop policy if exists "Public can read reviews" on public.game_reviews;
drop policy if exists "Anyone can create reviews" on public.game_reviews;
drop policy if exists "Users can insert reviews" on public.game_reviews;
drop policy if exists "Users can edit their own reviews" on public.game_reviews;

create policy "Public can read reviews"
on public.game_reviews
for select
using (true);

create policy "Users can insert reviews"
on public.game_reviews
for insert
with check (rating between 1 and 5 and length(trim(review)) > 0);

create policy "Users can edit their own reviews"
on public.game_reviews
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

notify pgrst, 'reload schema';
