-- FlashPortal V53 release polish
-- Run once if friend requests, notifications, owner delete, or game visibility feel stale.

create extension if not exists pgcrypto;

grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Owner game visibility / deletion persistence
create table if not exists public.game_visibility (
  game_id text primary key,
  hidden boolean not null default false,
  deleted boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  updated_by_email text,
  updated_at timestamptz not null default now()
);

alter table public.game_visibility add column if not exists hidden boolean not null default false;
alter table public.game_visibility add column if not exists deleted boolean not null default false;
alter table public.game_visibility add column if not exists updated_by uuid references auth.users(id) on delete set null;
alter table public.game_visibility add column if not exists updated_by_email text;
alter table public.game_visibility add column if not exists updated_at timestamptz not null default now();

alter table public.game_visibility enable row level security;
grant select on public.game_visibility to anon, authenticated;
grant insert, update, delete on public.game_visibility to authenticated;

drop policy if exists "Public can read game visibility" on public.game_visibility;
drop policy if exists "Owner can manage game visibility" on public.game_visibility;

create policy "Public can read game visibility"
on public.game_visibility for select
using (true);

create policy "Owner can manage game visibility"
on public.game_visibility for all to authenticated
using (lower(auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com')
with check (lower(auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

-- Friend requests: sender sees sent, target sees received, target can accept/decline.
create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users(id) on delete cascade,
  sender_email text,
  target text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.friend_requests add column if not exists sender_id uuid references auth.users(id) on delete cascade;
alter table public.friend_requests add column if not exists sender_email text;
alter table public.friend_requests add column if not exists target text;
alter table public.friend_requests add column if not exists status text not null default 'pending';
alter table public.friend_requests add column if not exists created_at timestamptz not null default now();
alter table public.friend_requests add column if not exists updated_at timestamptz not null default now();

alter table public.friend_requests enable row level security;
grant select, insert, update, delete on public.friend_requests to authenticated;

drop policy if exists "Users can insert friend requests" on public.friend_requests;
drop policy if exists "Users can see related friend requests" on public.friend_requests;
drop policy if exists "Users can update received friend requests" on public.friend_requests;
drop policy if exists "Users can delete related friend requests" on public.friend_requests;

create policy "Users can insert friend requests"
on public.friend_requests for insert to authenticated
with check (auth.uid() = sender_id or lower(sender_email) = lower(auth.jwt() ->> 'email'));

create policy "Users can see related friend requests"
on public.friend_requests for select to authenticated
using (
  auth.uid() = sender_id
  or lower(target) = lower(auth.jwt() ->> 'email')
  or lower(sender_email) = lower(auth.jwt() ->> 'email')
);

create policy "Users can update received friend requests"
on public.friend_requests for update to authenticated
using (lower(target) = lower(auth.jwt() ->> 'email'))
with check (lower(target) = lower(auth.jwt() ->> 'email'));

create policy "Users can delete related friend requests"
on public.friend_requests for delete to authenticated
using (
  auth.uid() = sender_id
  or lower(target) = lower(auth.jwt() ->> 'email')
  or lower(sender_email) = lower(auth.jwt() ->> 'email')
);

-- Platform announcements readable by everyone, owner writes them.
create table if not exists public.platform_announcements (
  id bigint generated by default as identity primary key,
  title text not null default 'FlashPortal Announcement',
  body text not null,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_by_email text,
  created_at timestamptz not null default now()
);

alter table public.platform_announcements enable row level security;
grant select on public.platform_announcements to anon, authenticated;
grant insert, update, delete on public.platform_announcements to authenticated;

drop policy if exists "Public can read active announcements" on public.platform_announcements;
drop policy if exists "Owner can insert announcements" on public.platform_announcements;
drop policy if exists "Owner can update announcements" on public.platform_announcements;
drop policy if exists "Owner can delete announcements" on public.platform_announcements;

create policy "Public can read active announcements"
on public.platform_announcements for select
using (active = true);

create policy "Owner can insert announcements"
on public.platform_announcements for insert to authenticated
with check (lower(auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

create policy "Owner can update announcements"
on public.platform_announcements for update to authenticated
using (lower(auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com')
with check (lower(auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

create policy "Owner can delete announcements"
on public.platform_announcements for delete to authenticated
using (lower(auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

-- Owner can mark submissions deleted/approved/declined so queue and game list stay synced.
alter table public.game_submissions enable row level security;
grant select, insert, update on public.game_submissions to authenticated;

drop policy if exists "Owner can update all submissions" on public.game_submissions;
create policy "Owner can update all submissions"
on public.game_submissions for update to authenticated
using (lower(auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com')
with check (lower(auth.jwt() ->> 'email') = 'isaac.akinola122@gmail.com');

notify pgrst, 'reload schema';
