-- FlashPortal V56 optional creator profile/follow persistence
-- Run only if you want follows stored in Supabase instead of local browser storage.

grant usage on schema public to anon, authenticated;

create table if not exists public.creator_follows (
  id bigint generated by default as identity primary key,
  creator_slug text not null,
  creator_name text not null,
  follower_id uuid references auth.users(id) on delete cascade,
  follower_email text not null,
  created_at timestamptz not null default now(),
  unique (creator_slug, follower_email)
);

alter table public.creator_follows enable row level security;

drop policy if exists "Anyone can read creator follows" on public.creator_follows;
drop policy if exists "Users can follow creators" on public.creator_follows;
drop policy if exists "Users can unfollow creators" on public.creator_follows;

create policy "Anyone can read creator follows"
on public.creator_follows
for select
using (true);

create policy "Users can follow creators"
on public.creator_follows
for insert
to authenticated
with check (lower(follower_email) = lower(auth.jwt() ->> 'email'));

create policy "Users can unfollow creators"
on public.creator_follows
for delete
to authenticated
using (lower(follower_email) = lower(auth.jwt() ->> 'email'));

grant select, insert, delete on public.creator_follows to authenticated;
grant select on public.creator_follows to anon;
grant usage, select on all sequences in schema public to anon, authenticated;

notify pgrst, 'reload schema';
