-- FlashPortal V58 Social Profiles / Creator Hub
-- Run this in Supabase SQL Editor for real profile pages and creator feed posts.

grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  username text unique,
  bio text,
  avatar_url text,
  banner_url text,
  followers bigint not null default 0,
  following bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles add column if not exists email text;
alter table public.user_profiles add column if not exists display_name text;
alter table public.user_profiles add column if not exists username text;
alter table public.user_profiles add column if not exists bio text;
alter table public.user_profiles add column if not exists avatar_url text;
alter table public.user_profiles add column if not exists banner_url text;
alter table public.user_profiles add column if not exists followers bigint not null default 0;
alter table public.user_profiles add column if not exists following bigint not null default 0;
alter table public.user_profiles add column if not exists created_at timestamptz not null default now();
alter table public.user_profiles add column if not exists updated_at timestamptz not null default now();

create unique index if not exists user_profiles_username_unique
on public.user_profiles (lower(username))
where username is not null;

alter table public.user_profiles enable row level security;
grant select, insert, update on public.user_profiles to anon, authenticated;

drop policy if exists "Public can read profiles" on public.user_profiles;
drop policy if exists "Users can create own profile" on public.user_profiles;
drop policy if exists "Users can update own profile" on public.user_profiles;

create policy "Public can read profiles"
on public.user_profiles for select
using (true);

create policy "Users can create own profile"
on public.user_profiles for insert
to authenticated
with check (auth.uid() = id);

create policy "Users can update own profile"
on public.user_profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create table if not exists public.social_posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  body text,
  image_url text,
  likes bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.social_posts add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.social_posts add column if not exists body text;
alter table public.social_posts add column if not exists image_url text;
alter table public.social_posts add column if not exists likes bigint not null default 0;
alter table public.social_posts add column if not exists created_at timestamptz not null default now();
alter table public.social_posts add column if not exists updated_at timestamptz not null default now();

alter table public.social_posts enable row level security;
grant select, insert, update, delete on public.social_posts to anon, authenticated;

drop policy if exists "Public can read social posts" on public.social_posts;
drop policy if exists "Users can create own social posts" on public.social_posts;
drop policy if exists "Users can update own social posts" on public.social_posts;
drop policy if exists "Users can delete own social posts" on public.social_posts;

create policy "Public can read social posts"
on public.social_posts for select
using (true);

create policy "Users can create own social posts"
on public.social_posts for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own social posts"
on public.social_posts for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own social posts"
on public.social_posts for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.social_comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.social_posts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.social_comments enable row level security;
grant select, insert, update, delete on public.social_comments to anon, authenticated;

drop policy if exists "Public can read social comments" on public.social_comments;
drop policy if exists "Users can create comments" on public.social_comments;

create policy "Public can read social comments"
on public.social_comments for select
using (true);

create policy "Users can create comments"
on public.social_comments for insert
to authenticated
with check (auth.uid() = user_id);

create or replace function public.increment_social_post_like(target_post_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_count bigint;
begin
  update public.social_posts
  set likes = likes + 1, updated_at = now()
  where id = target_post_id
  returning likes into new_count;

  return coalesce(new_count, 0);
end;
$$;

grant execute on function public.increment_social_post_like(bigint) to anon, authenticated;

notify pgrst, 'reload schema';
