-- FlashPortal V60 Profile + Follow Fix
-- Run once in Supabase SQL Editor.

grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  username text,
  bio text,
  avatar_url text,
  banner_url text,
  is_private boolean not null default false,
  followers bigint not null default 0,
  following bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles add column if not exists email text;
alter table public.user_profiles add column if not exists display_name text;
alter table public.user_profiles add column if not exists username text;
alter table public.user_profiles add column if not exists bio text;
alter table public.user_profiles add column if not exists avatar_url text;
alter table public.user_profiles add column if not exists banner_url text;
alter table public.user_profiles add column if not exists is_private boolean not null default false;
alter table public.user_profiles add column if not exists followers bigint not null default 0;
alter table public.user_profiles add column if not exists following bigint not null default 0;
alter table public.user_profiles add column if not exists created_at timestamptz not null default now();
alter table public.user_profiles add column if not exists updated_at timestamptz not null default now();

create unique index if not exists user_profiles_username_lower_unique
on public.user_profiles (lower(username))
where username is not null and username <> '';

alter table public.user_profiles enable row level security;
grant select, insert, update on public.user_profiles to anon, authenticated;

drop policy if exists "Public can read profiles" on public.user_profiles;
drop policy if exists "Users can create own profile" on public.user_profiles;
drop policy if exists "Users can update own profile" on public.user_profiles;

create policy "Public can read profiles" on public.user_profiles for select using (true);
create policy "Users can create own profile" on public.user_profiles for insert to authenticated with check (auth.uid() = id);
create policy "Users can update own profile" on public.user_profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

create table if not exists public.profile_follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(follower_id, following_id),
  check (follower_id <> following_id)
);

alter table public.profile_follows enable row level security;
grant select, insert, delete on public.profile_follows to anon, authenticated;

drop policy if exists "Public can read follows" on public.profile_follows;
drop policy if exists "Users can follow" on public.profile_follows;
drop policy if exists "Users can unfollow" on public.profile_follows;

create policy "Public can read follows" on public.profile_follows for select using (true);
create policy "Users can follow" on public.profile_follows for insert to authenticated with check (auth.uid() = follower_id);
create policy "Users can unfollow" on public.profile_follows for delete to authenticated using (auth.uid() = follower_id);

create or replace function public.refresh_profile_follow_counts(target_user_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.user_profiles
  set followers = (select count(*) from public.profile_follows where following_id = target_user_id),
      following = (select count(*) from public.profile_follows where follower_id = target_user_id),
      updated_at = now()
  where id = target_user_id;
end;
$$;

grant execute on function public.refresh_profile_follow_counts(uuid) to anon, authenticated;

create or replace function public.follow_profile(target_profile_id uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare current_user uuid := auth.uid(); follower_count bigint;
begin
  if current_user is null then raise exception 'Not logged in'; end if;
  if current_user = target_profile_id then raise exception 'You cannot follow yourself'; end if;
  insert into public.profile_follows (follower_id, following_id)
  values (current_user, target_profile_id)
  on conflict (follower_id, following_id) do nothing;
  perform public.refresh_profile_follow_counts(current_user);
  perform public.refresh_profile_follow_counts(target_profile_id);
  select followers into follower_count from public.user_profiles where id = target_profile_id;
  return jsonb_build_object('following', true, 'followers', coalesce(follower_count, 0));
end;
$$;

grant execute on function public.follow_profile(uuid) to authenticated;

create or replace function public.unfollow_profile(target_profile_id uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare current_user uuid := auth.uid(); follower_count bigint;
begin
  if current_user is null then raise exception 'Not logged in'; end if;
  delete from public.profile_follows where follower_id = current_user and following_id = target_profile_id;
  perform public.refresh_profile_follow_counts(current_user);
  perform public.refresh_profile_follow_counts(target_profile_id);
  select followers into follower_count from public.user_profiles where id = target_profile_id;
  return jsonb_build_object('following', false, 'followers', coalesce(follower_count, 0));
end;
$$;

grant execute on function public.unfollow_profile(uuid) to authenticated;

update public.user_profiles p
set followers = (select count(*) from public.profile_follows f where f.following_id = p.id),
    following = (select count(*) from public.profile_follows f where f.follower_id = p.id),
    updated_at = now();

notify pgrst, 'reload schema';
