-- ============================================================
-- FlashPortal V78 BACKEND HOTFIX
-- Run once after deploying V78.
-- Fixes:
-- - Real achievements tab/catalog + FlashPortal Pioneer legacy badge
-- - Creator feed persistent like/dislike state after refresh
-- - Comment delete function return-type conflict
-- - Faster feed RPC that returns posts + current user's reaction
-- ============================================================

create extension if not exists pgcrypto;
grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Safe compatibility columns.
alter table public.user_profiles
  add column if not exists is_deleted boolean default false,
  add column if not exists deleted_at timestamptz,
  add column if not exists last_seen_at timestamptz default now(),
  add column if not exists followers integer default 0,
  add column if not exists following integer default 0;

alter table public.social_posts
  add column if not exists likes integer default 0,
  add column if not exists dislikes integer default 0,
  add column if not exists comments integer default 0,
  add column if not exists is_private boolean default false,
  add column if not exists is_deleted boolean default false,
  add column if not exists video_url text,
  add column if not exists media_type text default 'image',
  add column if not exists updated_at timestamptz default now();

alter table public.social_comments
  add column if not exists is_deleted boolean default false;

create table if not exists public.social_post_reactions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.social_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (reaction in ('like','dislike')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(post_id, user_id)
);

alter table public.social_post_reactions enable row level security;
drop policy if exists "read social reactions" on public.social_post_reactions;
create policy "read social reactions" on public.social_post_reactions for select to anon, authenticated using (true);
drop policy if exists "insert own social reactions" on public.social_post_reactions;
create policy "insert own social reactions" on public.social_post_reactions for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "update own social reactions" on public.social_post_reactions;
create policy "update own social reactions" on public.social_post_reactions for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "delete own social reactions" on public.social_post_reactions;
create policy "delete own social reactions" on public.social_post_reactions for delete to authenticated using (user_id = auth.uid());

-- Achievement catalog compatibility.
create table if not exists public.achievement_catalog (
  code text primary key,
  title text not null,
  rarity text not null default 'common',
  category text not null default 'platform',
  game_id text,
  description text not null default '',
  unlock_hint text not null default '',
  points integer not null default 10,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.achievement_catalog
  add column if not exists category text not null default 'platform',
  add column if not exists game_id text,
  add column if not exists unlock_hint text not null default '',
  add column if not exists points integer not null default 10,
  add column if not exists is_hidden boolean not null default false;

do $$
declare c text;
begin
  select conname into c
  from pg_constraint
  where conrelid = 'public.achievement_catalog'::regclass
    and contype = 'c'
    and conname like '%rarity%check%'
  limit 1;

  if c is not null then
    execute format('alter table public.achievement_catalog drop constraint %I', c);
  end if;
end $$;

alter table public.achievement_catalog
  add constraint achievement_catalog_rarity_check
  check (rarity in ('legacy','mythic','legendary','epic','rare','uncommon','common'));

create table if not exists public.user_badges (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  badge_code text not null references public.achievement_catalog(code) on delete cascade,
  earned_at timestamptz not null default now(),
  unique(user_id, badge_code)
);

alter table public.achievement_catalog enable row level security;
alter table public.user_badges enable row level security;
drop policy if exists "read achievement catalog" on public.achievement_catalog;
create policy "read achievement catalog" on public.achievement_catalog for select to anon, authenticated using (true);
drop policy if exists "read user badges" on public.user_badges;
create policy "read user badges" on public.user_badges for select to anon, authenticated using (true);
drop policy if exists "insert own user badges" on public.user_badges;
create policy "insert own user badges" on public.user_badges for insert to authenticated with check (user_id = auth.uid());

create table if not exists public.platform_settings (
  key text primary key,
  value jsonb not null default 'true'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.platform_settings enable row level security;
drop policy if exists "read platform settings" on public.platform_settings;
create policy "read platform settings" on public.platform_settings for select to anon, authenticated using (true);

insert into public.platform_settings(key, value)
values ('early_build', 'true'::jsonb)
on conflict(key) do update set value=excluded.value, updated_at=now();

insert into public.achievement_catalog(code,title,rarity,category,game_id,description,unlock_hint,points,is_hidden)
values
('flashportal_pioneer','FlashPortal Pioneer','legacy','legacy',null,'Joined FlashPortal during the Early Build era before the official completed release.','Create an account before FlashPortal Official releases.',1000,false),
('profile_started','Profile Started','common','profile',null,'Saved your FlashPortal profile.','Save your profile.',10,false),
('profile_pic','Profile Picture','common','profile',null,'Added a profile picture.','Add a profile picture.',10,false),
('bio_added','Bio Added','common','profile',null,'Added a profile bio.','Add a bio to your profile.',10,false),
('first_post','First Post','common','social',null,'Posted your first update.','Create a profile post.',20,false),
('first_comment','First Comment','common','social',null,'Commented on a community post.','Comment on a post.',20,false),
('first_like','First Like','common','social',null,'Reacted to a community post.','Like or dislike a post.',20,false),
('first_message','First Message','uncommon','social',null,'Sent your first direct message.','Send a message.',40,false),
('first_rating','First Rating','common','games',null,'Rated your first game.','Rate any game.',20,false),
('first_review','First Review','uncommon','games',null,'Wrote your first public review.','Write a review.',40,false),
('first_save','First Save','common','games',null,'Saved your first game.','Save any game.',20,false),
('creator_start','Creator Start','uncommon','creator',null,'Uploaded or published your first game.','Upload a game.',50,false),
('rising_creator','Rising Creator','rare','creator',null,'Reached 5 followers.','Reach 5 followers.',150,false),
('community_spark','Community Spark','rare','social',null,'Made 10 comments or reactions.','Interact with community posts.',150,false),
('how_many_rings_first_run','How Many Rings Rookie','common','game','how-many-rings','Started a dynasty in How Many Rings.','Play How Many Rings once.',25,false),
('how_many_rings_dynasty','Dynasty Builder','rare','game','how-many-rings','Built a strong title-window run.','Reach a high ring count in How Many Rings.',200,false),
('legacy_league_first_snap','First Snap','common','game','legacy-league','Started a Legacy League career.','Play Legacy League once.',25,false),
('legacy_league_champion','League Champion','epic','game','legacy-league','Built a championship-level Legacy League save.','Win big in Legacy League.',350,false),
('guess_word_solver','Word Solver','common','game','guess-the-word','Solved your first Guess The Word puzzle.','Play Guess The Word.',25,false),
('guess_word_streak','Word Streak','rare','game','guess-the-word','Built a strong Guess The Word streak.','Keep winning Guess The Word rounds.',200,false),
('guess_celeb_spotter','Celeb Spotter','common','game','guess-the-celeb','Guessed your first celebrity correctly.','Play Guess The Celeb.',25,false),
('guess_celeb_master','Celeb Mastermind','epic','game','guess-the-celeb','Dominated Guess The Celeb clues.','Win difficult Guess The Celeb rounds.',350,false)
on conflict(code) do update set
  title=excluded.title,
  rarity=excluded.rarity,
  category=excluded.category,
  game_id=excluded.game_id,
  description=excluded.description,
  unlock_hint=excluded.unlock_hint,
  points=excluded.points,
  is_hidden=excluded.is_hidden;

-- Award Early Build legacy badge to every existing account/profile while early_build is true.
insert into public.user_badges(user_id, badge_code)
select id, 'flashportal_pioneer'
from public.user_profiles
where coalesce(is_deleted,false)=false
on conflict(user_id, badge_code) do nothing;

insert into public.user_badges(user_id, badge_code)
select id, 'profile_started'
from public.user_profiles
where coalesce(is_deleted,false)=false
on conflict(user_id, badge_code) do nothing;

insert into public.user_badges(user_id, badge_code)
select id, 'profile_pic'
from public.user_profiles
where coalesce(is_deleted,false)=false
  and coalesce(avatar_url,'') <> ''
on conflict(user_id, badge_code) do nothing;

insert into public.user_badges(user_id, badge_code)
select id, 'bio_added'
from public.user_profiles
where coalesce(is_deleted,false)=false
  and coalesce(bio,'') <> ''
on conflict(user_id, badge_code) do nothing;

create or replace function public.fp_award_early_build_badge()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce((select (value::text)::boolean from public.platform_settings where key='early_build'), true) = true then
    insert into public.user_badges(user_id,badge_code)
    values(new.id,'flashportal_pioneer')
    on conflict(user_id,badge_code) do nothing;
  end if;
  insert into public.user_badges(user_id,badge_code)
  values(new.id,'profile_started')
  on conflict(user_id,badge_code) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_award_early_build_badge on public.user_profiles;
create trigger trg_award_early_build_badge
after insert on public.user_profiles
for each row execute function public.fp_award_early_build_badge();

drop function if exists public.fp_delete_social_comment(bigint);

create or replace function public.fp_delete_social_comment(target_comment_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  target_post bigint;
begin
  if uid is null then
    raise exception 'login_required';
  end if;

  select post_id into target_post from public.social_comments where id=target_comment_id;
  if target_post is null then
    return false;
  end if;

  update public.social_comments sc
  set is_deleted=true
  where sc.id=target_comment_id
    and (
      sc.user_id=uid
      or exists(select 1 from public.social_posts sp where sp.id=sc.post_id and sp.user_id=uid)
    );

  update public.social_posts sp
  set comments=(
    select count(*)::integer
    from public.social_comments sc
    where sc.post_id=sp.id and coalesce(sc.is_deleted,false)=false
  )
  where sp.id=target_post;

  return true;
end;
$$;
grant execute on function public.fp_delete_social_comment(bigint) to authenticated;

create or replace function public.fp_set_social_reaction(target_post_id bigint, new_reaction text)
returns table(likes integer, dislikes integer, my_reaction text)
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  clean_reaction text := nullif(trim(lower(new_reaction)), '');
  like_count integer;
  dislike_count integer;
  final_reaction text;
begin
  if uid is null then
    raise exception 'login_required';
  end if;

  if clean_reaction not in ('like','dislike') and clean_reaction is not null then
    raise exception 'invalid_reaction';
  end if;

  if clean_reaction is null then
    delete from public.social_post_reactions where post_id=target_post_id and user_id=uid;
  elsif exists(select 1 from public.social_post_reactions where post_id=target_post_id and user_id=uid and reaction=clean_reaction) then
    delete from public.social_post_reactions where post_id=target_post_id and user_id=uid;
    clean_reaction := null;
  else
    insert into public.social_post_reactions(post_id,user_id,reaction,updated_at)
    values(target_post_id,uid,clean_reaction,now())
    on conflict(post_id,user_id)
    do update set reaction=excluded.reaction, updated_at=now();
  end if;

  select count(*)::integer into like_count from public.social_post_reactions where post_id=target_post_id and reaction='like';
  select count(*)::integer into dislike_count from public.social_post_reactions where post_id=target_post_id and reaction='dislike';
  select reaction into final_reaction from public.social_post_reactions where post_id=target_post_id and user_id=uid;

  update public.social_posts set likes=like_count, dislikes=dislike_count where id=target_post_id;

  insert into public.user_badges(user_id,badge_code)
  values(uid,'first_like')
  on conflict(user_id,badge_code) do nothing;

  return query select like_count, dislike_count, final_reaction;
end;
$$;
grant execute on function public.fp_set_social_reaction(bigint,text) to authenticated;

create or replace function public.fp_get_creator_feed(feed_limit integer default 25)
returns table(
  id bigint,
  user_id uuid,
  body text,
  image_url text,
  video_url text,
  media_type text,
  created_at timestamptz,
  likes integer,
  dislikes integer,
  comments integer,
  my_reaction text,
  author_username text,
  author_display_name text,
  author_avatar_url text,
  author_is_private boolean,
  author_last_seen_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    sp.id,
    sp.user_id,
    sp.body,
    sp.image_url,
    sp.video_url,
    sp.media_type,
    sp.created_at,
    coalesce(sp.likes,0)::integer,
    coalesce(sp.dislikes,0)::integer,
    coalesce(sp.comments,0)::integer,
    spr.reaction,
    up.username,
    up.display_name,
    up.avatar_url,
    coalesce(up.is_private,false),
    up.last_seen_at
  from public.social_posts sp
  left join public.user_profiles up on up.id=sp.user_id
  left join public.social_post_reactions spr on spr.post_id=sp.id and spr.user_id=auth.uid()
  where coalesce(sp.is_deleted,false)=false
    and coalesce(sp.is_private,false)=false
    and coalesce(up.is_deleted,false)=false
  order by sp.created_at desc
  limit feed_limit;
$$;
grant execute on function public.fp_get_creator_feed(integer) to anon, authenticated;

create or replace function public.fp_get_achievement_page(target_user_id uuid default null)
returns table(
  code text,
  title text,
  rarity text,
  category text,
  game_id text,
  description text,
  unlock_hint text,
  points integer,
  is_hidden boolean,
  earned boolean,
  earned_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    ac.code,
    ac.title,
    ac.rarity,
    ac.category,
    ac.game_id,
    ac.description,
    ac.unlock_hint,
    ac.points,
    ac.is_hidden,
    (ub.id is not null) as earned,
    ub.earned_at
  from public.achievement_catalog ac
  left join public.user_badges ub
    on ub.badge_code=ac.code
   and ub.user_id=coalesce(target_user_id, auth.uid())
  where ac.is_hidden=false or ub.id is not null
  order by
    case ac.rarity
      when 'legacy' then 0
      when 'mythic' then 1
      when 'legendary' then 2
      when 'epic' then 3
      when 'rare' then 4
      when 'uncommon' then 5
      else 6
    end,
    ac.points desc,
    ac.title asc;
$$;
grant execute on function public.fp_get_achievement_page(uuid) to anon, authenticated;

-- Backfill counters so UI matches the database after refresh.
update public.social_posts sp
set likes = coalesce(counts.total,0)
from (
  select post_id, count(*)::integer as total
  from public.social_post_reactions
  where reaction='like'
  group by post_id
) counts
where sp.id = counts.post_id;

update public.social_posts sp
set dislikes = coalesce(counts.total,0)
from (
  select post_id, count(*)::integer as total
  from public.social_post_reactions
  where reaction='dislike'
  group by post_id
) counts
where sp.id = counts.post_id;

update public.social_posts sp
set comments = coalesce(counts.total,0)
from (
  select post_id, count(*)::integer as total
  from public.social_comments
  where coalesce(is_deleted,false)=false
  group by post_id
) counts
where sp.id = counts.post_id;

create index if not exists social_posts_feed_v78_idx on public.social_posts(created_at desc) where coalesce(is_deleted,false)=false and coalesce(is_private,false)=false;
create index if not exists social_post_reactions_user_post_v78_idx on public.social_post_reactions(user_id, post_id);
create index if not exists social_post_reactions_post_reaction_v78_idx on public.social_post_reactions(post_id, reaction);
create index if not exists social_comments_post_v78_idx on public.social_comments(post_id, created_at) where coalesce(is_deleted,false)=false;
create index if not exists user_badges_user_v78_idx on public.user_badges(user_id, earned_at desc);

update public.platform_announcements
set active=false
where lower(coalesce(body,'')) in ('test','testing')
   or lower(coalesce(title,'')) in ('test','testing');

notify pgrst, 'reload schema';
