"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Save,Send,UserRound,EyeOff,Globe2} from "lucide-react";
import {supabase} from "../../lib/supabaseClient";
const clean=(v)=>String(v||"").toLowerCase().replace(/^@+/,"").replace(/[^a-z0-9_.]/g,"").slice(0,24);
const fallback=(u)=>({id:u?.id,email:u?.email,display_name:u?.user_metadata?.full_name||u?.email?.split("@")[0]||"player",username:clean(u?.email?.split("@")[0]||"player"),bio:"Playing games on FlashPortal.",avatar_url:u?.user_metadata?.avatar_url||"",banner_url:"",is_private:false,followers:0,following:0});
export default function Profile(){
 const [user,setUser]=useState(null),[profile,setProfile]=useState(null),[draft,setDraft]=useState(null),[posts,setPosts]=useState([]),[body,setBody]=useState(""),[img,setImg]=useState(""),[status,setStatus]=useState("");
 async function load(){const {data:s}=await supabase.auth.getSession();const u=s?.session?.user||null;setUser(u);if(!u)return;let fb=fallback(u);let {data,error}=await supabase.from("user_profiles").select("*").eq("id",u.id).maybeSingle();if(error)setStatus("Run V60 SQL, then refresh.");if(!data){await supabase.from("user_profiles").upsert(fb,{onConflict:"id"});data=fb}setProfile(data);setDraft(data);const {data:p}=await supabase.from("social_posts").select("*").eq("user_id",u.id).order("created_at",{ascending:false}).limit(50);setPosts(p||[])}
 useEffect(()=>{load()},[]);
 async function login(){await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/profile`}})}
 async function save(){if(!user)return;const payload={id:user.id,email:user.email,display_name:draft.display_name?.trim()||"FlashPortal Player",username:clean(draft.username),bio:draft.bio?.trim()||"",avatar_url:draft.avatar_url?.trim()||"",banner_url:draft.banner_url?.trim()||"",is_private:!!draft.is_private,updated_at:new Date().toISOString()};const {data,error}=await supabase.from("user_profiles").upsert(payload,{onConflict:"id"}).select("*").single();if(error){setStatus(`Profile save failed: ${error.message}. Run V60 SQL.`);return}setProfile(data);setDraft(data);setStatus("Profile saved.")}
 async function post(){if(!user||(!body.trim()&&!img.trim()))return;const {data,error}=await supabase.from("social_posts").insert({user_id:user.id,body:body.trim(),image_url:img.trim()}).select("*").single();if(error){setStatus(`Post failed: ${error.message}`);return}setPosts([data,...posts]);setBody("");setImg("");setStatus("Posted.")}
 if(!user)return <main className="social-home-page"><Link className="back-link" href="/"><ArrowLeft/> Back</Link><section className="profile-hero-card signed-out"><h1>Create your FlashPortal profile</h1><button onClick={login}>Login with Google</button></section></main>;
 const p=profile||fallback(user);
 return <main className="social-home-page"><Link className="back-link" href="/"><ArrowLeft/> Back to FlashPortal</Link>
 <section className="profile-hero-card"><div className="profile-banner" style={{backgroundImage:p.banner_url?`linear-gradient(90deg,rgba(0,0,0,.55),rgba(0,0,0,.05)),url(${p.banner_url})`:undefined}}/><div className="profile-main-row"><div className="profile-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<UserRound/>}</div><div><h1>{p.display_name}</h1><p>@{p.username} {p.is_private?"• Private":"• Public"}</p><span>{p.bio}</span></div><Link className="profile-edit-button" href={`/profile/${p.username||p.id}`}>View Public Page</Link></div><div className="profile-stats-row"><Link href={`/profile/${p.username||p.id}/followers`}><strong>{Number(p.followers||0)}</strong> Followers</Link><span><strong>{Number(p.following||0)}</strong> Following</span><span><strong>{posts.length}</strong> Posts</span></div></section>
 <section className="profile-edit-panel"><h2>Edit Your Profile</h2><label>Display Name<input value={draft?.display_name||""} onChange={e=>setDraft({...draft,display_name:e.target.value})}/></label><label>Username<input value={draft?.username||""} onChange={e=>setDraft({...draft,username:clean(e.target.value)})}/></label><label>Bio<textarea value={draft?.bio||""} onChange={e=>setDraft({...draft,bio:e.target.value})}/></label><label>Avatar / PFP Image URL<input value={draft?.avatar_url||""} onChange={e=>setDraft({...draft,avatar_url:e.target.value})} placeholder="https://..."/></label><label>Banner Image URL<input value={draft?.banner_url||""} onChange={e=>setDraft({...draft,banner_url:e.target.value})} placeholder="https://..."/></label><label className="privacy-toggle-row"><input type="checkbox" checked={!!draft?.is_private} onChange={e=>setDraft({...draft,is_private:e.target.checked})}/>{draft?.is_private?<EyeOff/>:<Globe2/>} Private profile</label><button onClick={save}><Save/> Save Profile</button>{status&&<p className="hub-status">{status}</p>}</section>
 <section className="social-layout"><aside className="social-sidebar-card"><h3>Profile Links</h3><Link href="/creator-hub">Creator Hub Feed</Link><Link href="/about">About / Roadmap</Link></aside><section className="social-feed-column"><article className="post-composer"><h2>Post an update</h2><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Share an update..."/><input value={img} onChange={e=>setImg(e.target.value)} placeholder="Optional image URL"/><button onClick={post}><Send/> Post</button></article>{posts.map(x=><article className="social-post-card" key={x.id}>{x.body&&<p>{x.body}</p>}{x.image_url&&<img className="post-image" src={x.image_url} alt=""/>}<span>{new Date(x.created_at).toLocaleDateString()}</span></article>)}</section></section></main>}
