"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Heart,MessageCircle,Search,UserRound,Users} from "lucide-react";
import {supabase} from "../../lib/supabaseClient";
export default function Hub(){
 const [user,setUser]=useState(null),[profiles,setProfiles]=useState([]),[posts,setPosts]=useState([]),[following,setFollowing]=useState([]),[q,setQ]=useState(""),[status,setStatus]=useState("");
 async function load(){const {data:s}=await supabase.auth.getSession();const u=s?.session?.user||null;setUser(u);const {data:ps}=await supabase.from("user_profiles").select("*").order("updated_at",{ascending:false}).limit(100);const {data:po}=await supabase.from("social_posts").select("*, user_profiles(display_name,username,avatar_url,is_private)").order("created_at",{ascending:false}).limit(100);setProfiles(ps||[]);setPosts(po||[]);if(u){const {data:f}=await supabase.from("profile_follows").select("following_id").eq("follower_id",u.id);setFollowing((f||[]).map(x=>x.following_id))}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{let n=q.toLowerCase().trim();return n?profiles.filter(p=>[p.display_name,p.username,p.bio,p.email].filter(Boolean).some(v=>String(v).toLowerCase().includes(n))):profiles},[profiles,q]);
 const visible=posts.filter(post=>!post.user_profiles?.is_private||post.user_id===user?.id||following.includes(post.user_id));
 async function toggle(p){if(!user){setStatus("Log in first to follow creators.");return}if(user.id===p.id){setStatus("That is your own profile.");return}let has=following.includes(p.id);let {data,error}=await supabase.rpc(has?"unfollow_profile":"follow_profile",{target_profile_id:p.id});if(error){setStatus(`Follow failed: ${error.message}. Run V60 SQL.`);return}setFollowing(has?following.filter(id=>id!==p.id):[...following,p.id]);setProfiles(profiles.map(x=>x.id===p.id?{...x,followers:Number(data?.followers??x.followers??0)}:x));}
 return <main className="creator-hub-page social-home-page"><Link className="back-link" href="/"><ArrowLeft/> Back to FlashPortal</Link><section className="creator-feed-hero"><span><Users/> Creator Hub</span><h1>Community Feed</h1><p>Posts, updates, images, and activity from FlashPortal creators and players.</p><label className="hub-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search creators..."/></label>{status&&<p className="hub-status">{status}</p>}</section><section className="creator-hub-feed-layout"><section className="hub-feed-panel"><h2>Latest Posts</h2>{visible.length?visible.map(post=><article className="social-post-card" key={post.id}><div className="post-author-row"><div className="mini-avatar">{post.user_profiles?.avatar_url?<img src={post.user_profiles.avatar_url} alt=""/>:<UserRound/>}</div><div><strong>{post.user_profiles?.display_name||"FlashPortal Player"}</strong><span>@{post.user_profiles?.username||"player"} • {new Date(post.created_at).toLocaleDateString()}</span></div></div>{post.body&&<p>{post.body}</p>}{post.image_url&&<img className="post-image" src={post.image_url} alt=""/>}<div className="post-actions"><button><Heart/> {Number(post.likes||0)}</button><button><MessageCircle/> Comment</button></div></article>):<article className="social-post-card empty"><h3>No posts yet</h3><p>Post from your profile page.</p></article>}</section><aside className="creator-list-panel"><h2>Creators</h2>{filtered.map(p=>{let has=following.includes(p.id),self=user?.id===p.id;return <article className="creator-mini-card" key={p.id}><div className="mini-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<UserRound/>}</div><div><strong>{p.display_name||"FlashPortal Creator"}</strong><span>@{p.username||"creator"}</span><p>{p.is_private&&!has&&!self?"Private profile":p.bio||"No bio yet."}</p><div className="creator-mini-stats"><Link href={`/profile/${p.username||p.id}/followers`}>{Number(p.followers||0)} followers</Link><small>{p.is_private?"Private":"Public"}</small></div><div className="creator-mini-actions"><Link href={`/profile/${p.username||p.id}`}>View Profile</Link>{!self&&<button onClick={()=>toggle(p)}>{has?"Following":"Follow"}</button>}</div></div></article>})}</aside></section></main>}
